# AUTOGENERATED FILE, run ./scripts/generate_kubectl_manifests.sh to generate.
resource "kubectl_manifest" "certificate" {
  yaml_body = file("kubectl-manifests/certificate.yaml")
}

resource "kubectl_manifest" "deployment" {
  yaml_body = file("kubectl-manifests/deployment.yaml")
}

resource "kubectl_manifest" "external-dns-deployment" {
  yaml_body = file("kubectl-manifests/external-dns-deployment.yaml")
}

resource "kubectl_manifest" "external-dns-rbac" {
  yaml_body = file("kubectl-manifests/external-dns-rbac.yaml")
}

resource "kubectl_manifest" "ingress" {
  yaml_body = file("kubectl-manifests/ingress.yaml")
}

resource "kubectl_manifest" "service" {
  yaml_body = file("kubectl-manifests/service.yaml")
}

