
rm kubectl-resources.tf
echo "# AUTOGENERATED FILE, run ./scripts/generate_kubectl_manifests.sh to generate." > kubectl-resources.tf
for file in k8s-manifests/*.yaml
do
  echo "$file"
  slug=`expr "$file" : '^.*/\([a-z\-]*\)\.*yaml'`
  FILE="$file" FILE_SLUG="$slug" envsubst < scripts/templates/kubectl_manifest.yaml.tmpl >> kubectl-resources.tf
done
